### ISSUE TITLE
PHP Webshell Broken

### ISSUE THREAD

**Issue by paragonsec** [DeimosC2/DeimosC2#2]
### Environment Data
* DeimosC2 Version: 1.0.0
* DeimosC2 Build: All
* Operating System: All

### Expected Behavior
The PHP webshell should work exactly the same as the ASPX webshell when using the functionality such as filebrowser

### Actual Behavior
It appears PHP breaks on filebrowser since the inclusion of pulling drives down for Windows on ASPX. The PHP shell should operate and send the same data format back to the Deimos server as the ASPX shell does.

### Steps to Reproduce Behavior
Generate and run the PHP shell on any PHP webserver and try to interact with it.

### Misc Information
N/A

**Comment by developeruz** [comment]
Help still wanted for Windows, especially on making `get_win_drives()` work

**Comment by sogonsec** [comment]
Merged in code for this ticket that seems to work as best it can for now. We are limited in what we have access to in a limited environment.
