### ISSUE TITLE
error while executing the compiled version of DeimosC2_windows on window10

### ISSUE THREAD

**Issue by him4nsh** [DeimosC2/DeimosC2#22]
The compiled binary shows the following error while running in Windows 10 version 2004 as shown in screenshot

![Capture](https://user-images.githubusercontent.com/33822810/89284931-1e847d00-d66d-11ea-8cf7-de9ca3c3146e.JPG)

**Comment by paragonsec** [comment]
I could not replicate this on Windows 10 version 2004. 

![image](https://user-images.githubusercontent.com/28866353/89324576-1ddbee80-d64d-11ea-935c-eedfe4acb166.png)

Did you keep the folder structure of the release?
You are running it with a user that has permissions to write to the resources folder?

I also ran this test with a manually set ```gopath``` and still couldn't replicate it.

![image](https://user-images.githubusercontent.com/28866353/89325563-9abb9800-d64e-11ea-807a-b5aba41cdb72.png)

**Comment by paragonsec** [comment]
Closing as we can't replicate this issue on Windows version 2004.
