### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by initstring** [DeimosC2/DeimosC2#28]
Hey Deimos team!

First up, THANK YOU SO MUCH for your hard work. This tool is looking really awesome and your time and effort is greatly appreciated.

Also the UI just looks damn cool and I feel like a super hacker when I log in. Well done.

Anyway, I think I have a simple issue. When entering an int (like not using a decimal) into fields like `Delay` in `AgentOptions`, the agents will silently not compile. I believe this is due to a type error. When trying to manually compile the agent, I see this:

```
$ go build .
# github.com/DeimosC2/DeimosC2/resources/listenerresources/c8c9e5eb-5ddb-4fb5-93d9-7cf09ee1dd25
./QUIC_agent.go:81:28: cannot use delay (type int) as type float64 in argument to agentfunctions.SleepDelay
./QUIC_agent.go:253:9: cannot use n (type float64) as type int in assignment
```

### Environment Data
* DeimosC2 Version: 1.1.0
* DeimosC2 Build: ???
* Operating System: Ubuntu 18.04

### Expected Behavior

Agents to compile

### Actual Behavior

UI tells me agents have compiled, but they have not! I slam my head on the desk for an hour trying to figure out what I did wrong.

### Steps to Reproduce Behavior

- Create a new listener
- Set the "Delay" under "AgentOptions" to "1"
- See no agents compiled
- Try the "Generate Agent" button and see the same behaviour

### Misc Information

Probably just some input validation in the web UI swapping it to a float would do the trick (or even just a clear instruction to do so)

**Comment by paragonsec** [comment]
Thanks @initstring for the feedback and finding this bug! Developeruz did an amazing job on the UI! Once we confirm the PR fixes the issue it will be pushed to the dev branch.

**Comment by paragonsec** [comment]
Thanks again @initstring for finding this! It is now in the dev branch and fixed. 

I did find another area of improvement we will work on thanks to this which is doing validation on port as a int as well but right now the agents are expecting that as a string so will need to change it in a few areas.
