### ISSUE TITLE
Request failed with status code 406  Return : Maybe go away?

### ISSUE THREAD

**Issue by Me10nc** [DeimosC2/DeimosC2#92]
### Environment Data
* DeimosC2 Version:
* DeimosC2 Build:
* Operating System:CentOS7
### Expected Behavior
Created Successfully
### Actual Behavior
Request failed with status code 406

**Comment by CharlesDardaman** [comment]
This should be an error when someone tries to create the inital admin after its already been created.
https://github.com/DeimosC2/DeimosC2/blob/9d62925a96b10c2228fd212d95a70f270cb5680d/c2/webserver/webserver.go#L482
